name: Run Python Script

on:
  push:  # Trigger on push events
    branches:
      - main  # Specify branch (e.g., main or master)
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version

      # Step 3: Install dependencies (if required)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run the Python script
      - name: Run Python Script
        run: python sample_script.py
